// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobTasks.Data;

namespace MobTasks.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200513122200_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("MobTasks.Domain.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MobTasks.Domain.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MobTasks.Domain.Task", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId1");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("MobTasks.Domain.Member", b =>
                {
                    b.HasOne("MobTasks.Domain.Course", null)
                        .WithMany("Members")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("MobTasks.Domain.Task", b =>
                {
                    b.HasOne("MobTasks.Domain.Course", "Course")
                        .WithMany("Tasks")
                        .HasForeignKey("CourseId1");
                });
#pragma warning restore 612, 618
        }
    }
}
